### ISSUE TITLE
Unable to install saftetensors on MacBook m1

### ISSUE THREAD

**Issue by soumyajit-kavida** [huggingface/safetensors#330] opened 2023-08-18 04:22 UTC
### System Info

System - Macbook M1
OS - Sonoma 14.0
Python - 3.9.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Reproduction

```pip install safe tensors```

![Screenshot 2023-08-17 at 11 13 13 PM](https://github.com/huggingface/safetensors/assets/142385495/f991112b-cfb6-40ec-ad92-0c6c6491c391)

### Expected behavior

Should install properly

**Comment by Nathlmt** [comment] 2023-08-18 06:42
same issue

**Comment by Narsil** [comment] 2023-08-18 09:11
Is it better now ?, Just uploaded the prebuilt wheels.

**Comment by Narsil** [comment] 2023-08-18 10:01
Maybe not: https://github.com/huggingface/safetensors/actions/runs/5900779459/job/16006035825#step:7:129

**Comment by conderls** [comment] 2023-08-18 10:03
same issue on mac with intel chip
py3.8

one can fallback to v0.3.1 which can be installed properly.

**Comment by Narsil** [comment] 2023-08-18 10:07
@conderls MacOS 14 or MacOS 12 ?

**Comment by conderls** [comment] 2023-08-18 10:12
> @conderls MacOS 14 or MacOS 12 ?

MacOS 13.4.1 (c)

**Comment by Narsil** [comment] 2023-08-18 10:28
Can you try `pip install https://files.pythonhosted.org/packages/de/17/3bd70f4873bfb2f78d2c92a8ae9ae078a9cfd20b36e928f996d5c77dc064/safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl` ?

This wheel is already built for macos 13 + Python 3.8.....

**Comment by conderls** [comment] 2023-08-19 02:30
> Can you try `pip install https://files.pythonhosted.org/packages/de/17/3bd70f4873bfb2f78d2c92a8ae9ae078a9cfd20b36e928f996d5c77dc064/safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl` ?
> 
> This wheel is already built for macos 13 + Python 3.8.....

I gave it a shot and an ERROR raised.

```bash
$ sw_vers
ProductName:            macOS
ProductVersion:         13.4.1
ProductVersionExtra:    (c)
BuildVersion:           22F770820d

$ python --version
Python 3.8.15

$ pip install https://files.pythonhosted.org/packages/de/17/3bd70f4873bfb2f78d2c92a8ae9ae078a9cfd20b36e928f996d5c77dc064/safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl
ERROR: safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl is not a supported wheel on this platform.
```

I tried `pip install safetensors` as well on py3.7.4/3.10.0 env, same error raised as the author mentioned above.

**Comment by ubersupageek** [comment] 2023-08-21 03:00
Having same issue and have tried suggested solutions to no avail. Any assistance would be appreciated. macOS 13.4 & Python 3.8.17. Thanks in advance.

ex: pip install https://files.pythonhosted.org/packages/de/17/3bd70f4873bfb2f78d2c92a8ae9ae078a9cfd20b36e928f996d5c77dc064/safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl
ERROR: safetensors-0.3.2-cp38-cp38-macosx_13_0_x86_64.whl is not a supported wheel on this platform.

**Comment by soumyajit-kavida** [comment] 2023-08-21 05:47
> Maybe not: https://github.com/huggingface/safetensors/actions/runs/5900779459/job/16006035825#step:7:129
> 
> In the mean time
> 
> ```
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> pip install setuptools-rust
> pip install safetensors
> ```
> 
> Should work.

@Narsil This Solution works but for python version 3.11.9 not for 3.9.0

**Comment by Narsil** [comment] 2023-08-21 07:25
@soumyajit-kavida It works for every python version, this installs from source.

@ubersupageek Also on intel ?

**Comment by Narsil** [comment] 2023-08-21 12:04
I cannot reproduce on Mac 13.4 in AWS (intel).

**Comment by ubersupageek** [comment] 2023-08-21 19:49
safe tensors installed after upgrading to python 3.11

**Comment by ubersupageek** [comment] 2023-08-21 20:15
Is there a way to make it work with python 3.8?

**Comment by soumyajit-kavida** [comment] 2023-08-22 07:07
@ubersupageek Same for me. I was unable to install them on 3.9 or 3.8

**Comment by soumyajit-kavida** [comment] 2023-08-22 07:08
@Narsil It happens on Arm architectures most probably, and works for Python >3.11

**Comment by Narsil** [comment] 2023-08-22 09:25
Ok I finally managed to upload some prebuilt binaries usable with pip for conda....

**Comment by joshua-fitzmaurice** [comment] 2023-08-23 16:24
I think this is just an issues with 0.3.3. I was able to access binaries for 0.3.2 via pip so am happy with that for now

**Comment by Narsil** [comment] 2023-08-24 12:29
Windows 64bit was missing, should be fine now.

Sorry for the mess, I had to revamp the release scripts from scratch because of the M1/Mac/Conda mess (which didn't happen with the previous scripts in April...).

**Comment by casperdcl** [comment] 2023-08-24 20:20
Yes looks like [0.3.2 had pre-built aarch64 wheels](https://pypi.org/project/safetensors/0.3.2/#files) while [0.3.3 doesn't](https://pypi.org/project/safetensors/0.3.3/#files)

**Comment by Narsil** [comment] 2023-08-24 21:44
It's still taking ages. (6h+).
I'm pretty sure the job is being throttled by GH at this point. I have a big rework to move to maturin in order to fix this.

**Comment by Narsil** [comment] 2023-08-24 21:48
https://github.com/huggingface/safetensors/actions/runs/5952077724

**Comment by Narsil** [comment] 2023-08-25 08:34
For anyone that had issues @casperdcl could you try `pip install safetensors==0.3.3.post1` I had to rewrite everything to get those builds actually finishing.

It's a yanked version for now, but at least it should prove it could work on currently missing platforms.

Also closing this in favor of https://github.com/huggingface/safetensors/issues/346 given it's working on M1

**Closed by Narsil** 2023-08-25 08:34 UTC
